language: python
os: linux
dist: xenial
python: 3.9
sudo: true
install:
  pip install -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov